---
# tasks file for tamay.firewalld

- name: "Install firewalld"
  package:
    state: present
    name: firewalld

- name: "Start firewalld"
  service:
    name: firewalld
    state: started
    enabled: yes

- name: "Configure service rules"
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item.service }}"
    state: "{{ item.state | default('enabled') }}"
    zone: "{{ item.zone | default('public') }}"
  loop: "{{ firewalld_service }}"

- name: "Configure port rules"
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item.port }}"
    state: "{{ item.state | default('enabled') }}"
    zone: "{{ item.zone | default('public') }}"
  loop: "{{ firewalld_port }}"
